boot.o: boot.S multiboot.h x86_desc.h types.h
ex_wrapper.o: ex_wrapper.S
int_wrapper.o: int_wrapper.S
x86_desc.o: x86_desc.S x86_desc.h types.h
ex_handler.o: ex_handler.c ex_handler.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h ex_wrapper.h int_wrapper.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h keyboard.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h
lib.o: lib.c lib.h types.h
rtc.o: rtc.c
tests.o: tests.c tests.h x86_desc.h types.h lib.h
